# Basic tuning for jittery robots
use_sim_time: true
odom_frame: odom
base_frame: base_link
map_frame: map

# Optimization
enable_interactive_mode: true
use_scan_matching: true
scan_buffer_size: 10  # Smooths over jitter
expected_num_scan_points: 1081  # Match your merged scan size


# Loop closure
loop_closure_min_chain_size: 3
loop_closure_search_distance: 5.0